datestr;fio;email;text
20260307-144140;Timur Bai Rash;sdf@sdmfn.sdf;Hell Yeah
20260307-145012;ddfgd;sdfdfgdfgdfgdfgdfgsd@sdfsd.dfgdf;sdfgsdfgesrgvregdkfjvhilurhegkughaergkhakeusghvalkhenrgkuierh
20260307-145622;dfghfgdh;zxfglkjahg@lksdfj.sdlfkj;urmom
20260307-215226;Timur Bai Rash;timur.univercity@gmail.com;aboba
20260307-215814;sdfds sdfsd ssdf;timtimch123@gmail.com;Hello World!
20260307-144140;Timur Bai Rash;sdf@sdmfn.sdf;Hell Yeah
20260307-145012;ddfgd;sdfdfgdfgdfgdfgdfgsd@sdfsd.dfgdf;sdfgsdfgesrgvregdkfjvhilurhegkughaergkhakeusghvalkhenrgkuierh
20260307-145622;dfghfgdh;zxfglkjahg@lksdfj.sdlfkj;urmom
20260307-215226;Timur Bai Rash;timur.univercity@gmail.com;aboba
20260307-215814;sdfds sdfsd ssdf;timtimch123@gmail.com;Hello World!
20260307-144140;Timur Bai Rash;sdf@sdmfn.sdf;Hell Yeah
20260307-145012;ddfgd;sdfdfgdfgdfgdfgdfgsd@sdfsd.dfgdf;sdfgsdfgesrgvregdkfjvhilurhegkughaergkhakeusghvalkhenrgkuierh
20260307-145622;dfghfgdh;zxfglkjahg@lksdfj.sdlfkj;urmom
20260307-215226;Timur Bai Rash;timur.univercity@gmail.com;aboba
20260307-215814;sdfds sdfsd ssdf;timtimch123@gmail.com;Hello World!
20260307-144140;Urmom;ахахахаха@хаххахха.ахх;Aboba
